version: '2.15.1'
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - ./.env_docker
    ports:
      - "6379:6379"
    restart: on-failure
  db:
    image: postgres:15.2
    environment:
      POSTGRES_PASSWORD: PG_PASSWORD
    env_file:
      - ./.env_docker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
  bot:
    build: .
    command: sh -c "python -m bot"
    env_file:
      - ./.env_docker
    depends_on:
      - db
      - redis
    restart: always

volumes:
  pgdata: